<a href="https://colab.research.google.com/github/Kggzzz/Project_2021_matchingcolor/blob/main/Test_datapoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import cv2
import numpy as np

In [2]:
!pip install azure-storage-blob==2.1.0

     |████████████████████████████████| 88 kB 3.5 MB/s 
     |████████████████████████████████| 47 kB 4.2 MB/s 
     |████████████████████████████████| 3.6 MB 34.4 MB/s 


In [3]:
from azure.storage.blob import BlockBlobService
import os
blob_service_client = BlockBlobService(account_name='dent01', account_key='CuShY0B4TZJ84TjzPpaHxyrHOpO73aGXeCpdVq7x26OjIlQ1HOz+3DVc9pDEj9BdcEL8odFuTRF0mOAE+aCgiw==')

In [4]:
img = '342AE035-E0F5-4DEF-988E-27F570C725B2.png'

In [73]:
list_total = list()
S5_double = img
full_path_to_file2 = os.path.join(S5_double) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(S5_double)
S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
S5meanrefA1_1 = list()
for i in range(S5RGB_imgA1A1_1.shape[0]): 
    for j in range(S5RGB_imgA1A1_1.shape[1]): 
          if 1769<i<1881 and 2019<j<2131 :
             G1 =  S5RGB_imgA1A1_1[i:,j:]
          if 1770<i<1880 and 2015<j<2145 :
             G1 =  S5RGB_imgA1A1_1[i:,j:]
# S5meanrefA1_1 = np.array(S5meanrefA1_1)
# S5meanA1_2 = np.array(S5meanrefA1_1)
# S5rgbrefA1_1 = list()
# for i in range(3):
#   S5rgbrefA1_1.append(S5meanrefA1_1[:,i].mean())
#   S5rgbrefA1_1.append(S5meanA1_2[:,i].mean())
# list_total.append(S5rgbrefA1_1)

In [74]:
G1 

array([[[225, 206, 176],
        [226, 207, 177],
        [225, 206, 176],
        ...,
        [ 57,  55,  58],
        [ 62,  60,  63],
        [ 63,  61,  64]],

       [[225, 206, 176],
        [224, 205, 175],
        [220, 201, 171],
        ...,
        [ 61,  59,  62],
        [ 61,  59,  62],
        [ 58,  56,  59]],

       [[223, 204, 174],
        [222, 203, 173],
        [221, 202, 172],
        ...,
        [ 59,  57,  60],
        [ 59,  57,  60],
        [ 60,  58,  61]],

       ...,

       [[216, 203, 187],
        [219, 206, 190],
        [224, 208, 193],
        ...,
        [ 28,  24,  23],
        [ 39,  35,  34],
        [ 39,  35,  34]],

       [[216, 203, 187],
        [217, 204, 188],
        [221, 205, 190],
        ...,
        [ 28,  24,  23],
        [ 25,  21,  20],
        [ 25,  21,  20]],

       [[217, 204, 188],
        [216, 203, 187],
        [218, 202, 187],
        ...,
        [ 37,  33,  32],
        [ 19,  15,  14],
        [  4,   0,   0]]

In [62]:
# list_total = list()
# S5_double = img
# full_path_to_file2 = os.path.join(S5_double) 
# blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
# imagee = cv2.imread(S5_double)
# S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
# S5meanrefA1_1 = list()
# for i in range(S5RGB_imgA1A1_1.shape[0]): 
#     for j in range(S5RGB_imgA1A1_1.shape[1]): 
#           if 1769<i<1881 and 2019<j<2131 :
#              new_img = S5RGB_imgA1A1_1[i][j]
#           if 1770<i<1880 and 2015<j<2145 :
#              new_img = S5RGB_imgA1A1_1[i][j]
# S5meanrefA1_1 = np.array(S5meanrefA1_1)
# S5meanA1_2 = np.array(S5meanrefA1_1)
# S5rgbrefA1_1 = list()
# for i in range(3):
#   S5rgbrefA1_1.append(S5meanrefA1_1[:,i].mean())
#   S5rgbrefA1_1.append(S5meanA1_2[:,i].mean())
# list_total.append(S5rgbrefA1_1)

In [63]:
new_img

array([225, 206, 176], dtype=uint8)

In [58]:
S5RGB_imgA1A1_1.shape

(3024, 4032, 3)

In [39]:
# list_total = list()
# S5_double = img
# full_path_to_file2 = os.path.join(S5_double) 
# blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
# imagee = cv2.imread(S5_double)
# S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
# S5meanrefA1_1 = list()
# for i in range(S5RGB_imgA1A1_1.shape[0]): 
#   for j in range(S5RGB_imgA1A1_1.shape[1]): 
#       if 1769<i<1881 and 2019<j<2131 :
#           S5meanrefA1_1.append(S5RGB_imgA1A1_1[i][j]) 
#       if 1770<i<1880 and 2015<j<2145 :
#           S5meanrefA1_1.append(S5RGB_imgA1A1_1[i][j])
# S5meanrefA1_1 = np.array(S5meanrefA1_1)
# S5meanA1_2 = np.array(S5meanrefA1_1)
# S5rgbrefA1_1 = list()
# for i in range(3):
#   S5rgbrefA1_1.append(S5meanrefA1_1[:,i].mean())
#   S5rgbrefA1_1.append(S5meanA1_2[:,i].mean())
# list_total.append(S5rgbrefA1_1)

In [40]:
S5meanrefA1_1

array([[230, 214, 181],
       [231, 215, 182],
       [233, 217, 184],
       ...,
       [222, 203, 173],
       [222, 203, 173],
       [225, 206, 176]], dtype=uint8)