<a href="https://colab.research.google.com/github/Kggzzz/Project_2021_matchingcolor/blob/main/Test_datapoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
import cv2
import numpy as np

In [11]:
!pip install azure-storage-blob==2.1.0

In [12]:
from azure.storage.blob import BlockBlobService
import os
blob_service_client = BlockBlobService(account_name='dent01', account_key='CuShY0B4TZJ84TjzPpaHxyrHOpO73aGXeCpdVq7x26OjIlQ1HOz+3DVc9pDEj9BdcEL8odFuTRF0mOAE+aCgiw==')

In [13]:
img = '342AE035-E0F5-4DEF-988E-27F570C725B2.png'

In [ ]:
list_total1 = list()
list_total2 = list()
list_total3 = list()
S5_double = img
full_path_to_file2 = os.path.join(S5_double) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(S5_double)
S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
S5meanrefA1_1 =  S5RGB_imgA1A1_1[1769:1881,2019:2131] #ลองดูพิกัดใหม่
S5meanA1_2 = S5RGB_imgA1A1_1[1770:1880,2015:2145]
S5meanrefA1_1 = np.array(S5meanrefA1_1[0])
S5meanA1_2 = np.array(S5meanA1_2[0])
S5rgbrefA1_1 = list()
S5rgbA1_2 = list()
for i in range(3):
  S5rgbrefA1_1.append(S5meanrefA1_1[:,i].mean())
  S5rgbA1_2.append(S5meanA1_2[:,i].mean())
list_total1.append(S5rgbrefA1_1)
list_total2.append(S5rgbA1_2)
list_total1[0].extend(list_total2[0])
list_total3 = list_total1 

In [ ]:
list_total3

[[231.90178571428572,
  215.35714285714286,
  184.02678571428572,
  231.0,
  214.5076923076923,
  182.98461538461538]]

In [ ]:
S5rgbrefA1_1

[231.90178571428572, 215.35714285714286, 184.02678571428572]

In [ ]:
list_total3

[[231.90178571428572,
  215.35714285714286,
  184.02678571428572,
  231.0,
  214.5076923076923,
  182.98461538461538]]

In [ ]:
list_total

[([231.90178571428572, 215.35714285714286, 184.02678571428572],
  [231.0, 214.5076923076923, 182.98461538461538])]

In [ ]:
S5meanrefA1_1.shape

(112, 3)

In [ ]:
G1[0]

array([[225, 206, 176],
       [226, 207, 177],
       [225, 206, 176],
       ...,
       [ 57,  55,  58],
       [ 62,  60,  63],
       [ 63,  61,  64]], dtype=uint8)

In [ ]:
# list_total = list()
# S5_double = img
# full_path_to_file2 = os.path.join(S5_double) 
# blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
# imagee = cv2.imread(S5_double)
# S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
# S5meanrefA1_1 = list()
# for i in range(S5RGB_imgA1A1_1.shape[0]): 
#     for j in range(S5RGB_imgA1A1_1.shape[1]): 
#           if 1769<i<1881 and 2019<j<2131 :
#              new_img = S5RGB_imgA1A1_1[i][j]
#           if 1770<i<1880 and 2015<j<2145 :
#              new_img = S5RGB_imgA1A1_1[i][j]
# S5meanrefA1_1 = np.array(S5meanrefA1_1)
# S5meanA1_2 = np.array(S5meanrefA1_1)
# S5rgbrefA1_1 = list()
# for i in range(3):
#   S5rgbrefA1_1.append(S5meanrefA1_1[:,i].mean())
#   S5rgbrefA1_1.append(S5meanA1_2[:,i].mean())
# list_total.append(S5rgbrefA1_1)

In [ ]:
new_img

array([225, 206, 176], dtype=uint8)

In [ ]:
S5RGB_imgA1A1_1.shape

(3024, 4032, 3)

In [ ]:
# list_total = list()
# S5_double = img
# full_path_to_file2 = os.path.join(S5_double) 
# blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
# imagee = cv2.imread(S5_double)
# S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
# S5meanrefA1_1 = list()
# for i in range(S5RGB_imgA1A1_1.shape[0]): 
#   for j in range(S5RGB_imgA1A1_1.shape[1]): 
#       if 1769<i<1881 and 2019<j<2131 :
#           S5meanrefA1_1.append(S5RGB_imgA1A1_1[i][j]) 
#       if 1770<i<1880 and 2015<j<2145 :
#           S5meanrefA1_1.append(S5RGB_imgA1A1_1[i][j])
# S5meanrefA1_1 = np.array(S5meanrefA1_1)
# S5meanA1_2 = np.array(S5meanrefA1_1)
# S5rgbrefA1_1 = list()
# for i in range(3):
#   S5rgbrefA1_1.append(S5meanrefA1_1[:,i].mean())
#   S5rgbrefA1_1.append(S5meanA1_2[:,i].mean())
# list_total.append(S5rgbrefA1_1)

In [ ]:
S5meanrefA1_1

array([[230, 214, 181],
       [231, 215, 182],
       [233, 217, 184],
       ...,
       [222, 203, 173],
       [222, 203, 173],
       [225, 206, 176]], dtype=uint8)

In [ ]:
S5meanrefA1_1.shape

(26382, 3)

In [16]:
list_total12 = list()
list_total22 = list()
S5_double2 = img
image2  = cv2.imread(S5_double2) #RGB
S1RGB_imgA1A1_12= cv2.cvtColor(image2, cv2.COLOR_BGR2RGB)
S1meanrefA1_12 = list()
for i in range(S1RGB_imgA1A1_12.shape[0]): 
  for j in range(S1RGB_imgA1A1_12.shape[1]): 
        if 1769<i<1881 and 2019<j<2131 :
          S1meanrefA1_12.append(S1RGB_imgA1A1_12[i][j]) 
S1meanrefA1_12 = np.array(S1meanrefA1_12)
S1rgbrefA1_12 = list()
for i in range(3):
   S1rgbrefA1_12.append(S1meanrefA1_12[:,i].mean())
list_total12.append(S1rgbrefA1_12)

S1meanA1_22 = list()
for i in range(S1RGB_imgA1A1_12.shape[0]): 
  for j in range(S1RGB_imgA1A1_12.shape[1]): 
      if 1770<i<1880 and 2015<j<2145 :
        S1meanA1_22.append(S1RGB_imgA1A1_12[i][j])  
S1meanA1_22 = np.array(S1meanA1_22)
# S1rgbA1_2 = list()
# for i in range(3):
#   S1rgbA1_2.append(S1meanA1_2[:,i].mean())
# list_total2.append(S1rgbA1_2)
# list_total1[0].extend(list_total2[0])
# list_total3 = list_total1

In [ ]:
list_total3 

[[227.33065497930363,
  209.00048697345994,
  176.54403051700348,
  227.05412132849727,
  208.74084346774768,
  176.32529692056042]]

In [24]:
S1meanrefA1_12

array([[230, 214, 181],
       [231, 215, 182],
       [233, 217, 184],
       ...,
       [222, 203, 173],
       [222, 203, 173],
       [225, 206, 176]], dtype=uint8)

In [22]:
S1meanrefA1_12.shape

(12321, 3)

In [ ]:
# list_total1 = list()
# for img in A1_set11['Img']:
#   S1_double = img
#   full_path_to_file2 = os.path.join(S1_double) 
#   blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
#   imgS1_A1A1_1  = cv2.imread(S1_double) #RGB
#   S1RGB_imgA1A1_1= cv2.cvtColor(imgS1_A1A1_1, cv2.COLOR_BGR2RGB)
#   S1meanrefA1_1 = list()
#   S1meanrefA1_2 = list()
#   for i in range(S1RGB_imgA1A1_1.shape[0]): 
#      for j in range(S1RGB_imgA1A1_1.shape[1]): 
#                 if 1769<i<1881 and 2019<j<2131 :
#                   S1meanrefA1_1.append(S1RGB_imgA1A1_1[i][j]) 
#                 if 1770<i<1880 and 2015<j<2145 :
#                   S1meanrefA1_2.append(S1RGB_imgA1A1_1[i][j])
#   S1meanrefA1_1 = np.array(S1meanrefA1_1)
#   S1meanrefA1_2 = np.array(S1meanrefA1_2)
#   S1rgbrefA1_1 = list()
#   S1rgbrefA1_2 = list()
#   for i in range(3):
#     S1rgbrefA1_1.append(S1meanrefA1_1[:,i].mean())
#     S1rgbrefA1_2.append(S1meanrefA1_2[:,i].mean())
#   list_total1.append((S1rgbrefA1_1,S1rgbrefA1_2))

In [29]:
# S5_double = img
# full_path_to_file2 = os.path.join(S5_double) 
# blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
# imagee = cv2.imread(S5_double)
# S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)

# S5meanrefA1_1 =  S5RGB_imgA1A1_1[1769:1881,2019:2131]
# S5meanA1_2 = S5RGB_imgA1A1_1[1770:1880,2015:2145]
# S5refA1_1 = np.array(S5meanrefA1_1[0])
# S5refA1_2 = np.array(S5meanA1_2[0])
# Rref = S5refA1_1[:,0].mean()
# Gref = S5refA1_1[:,1].mean()
# Bref = S5refA1_1[:,2].mean()
# R = S5refA1_2[:,0].mean()
# G = S5refA1_2[:,1].mean()
# B = S5refA1_2[:,2].mean()
    
# list_total = list()
# list_total.append(Rref)
# list_total.append(Gref)
# list_total.append(Bref)
# list_total.append(R)
# list_total.append(G)
# list_total.append(B)

In [30]:
S5meanrefA1_1.shape

(112, 112, 3)

In [ ]:
# list_total

[231.90178571428572,
 215.35714285714286,
 184.02678571428572,
 231.0,
 214.5076923076923,
 182.98461538461538]

In [ ]:
# list_total2 = list()
# list_total2.append(list_total)

In [ ]:
# list_total2

[[231.90178571428572,
  215.35714285714286,
  184.02678571428572,
  231.0,
  214.5076923076923,
  182.98461538461538]]

#ตาราง

In [ ]:
from google.colab import drive 
drive.mount('/content/drive')

In [ ]:
path = '/content/drive/My Drive/shadeimg'

In [ ]:
import os

In [ ]:
os.listdir(path)

In [ ]:
AA = os.path.join(path,'Color-checkerDD.xlsx')

In [ ]:
A1_set1= pd.read_excel(AA, sheet_name='D3_1')
A1_set1

In [ ]:
A1_set1.rename(columns={"ฝั่งซ้าย": "Ref"},inplace=True)

In [ ]:
A1_set1.rename(columns={"ฝั่งขวา":"Shad"},inplace=True)

In [ ]:
A1_set1.rename(columns={"ชื่อไฟล์ข้อมูล":"Img"},inplace=True)

In [ ]:
A1_set1

In [ ]:
table1= A1_set1[['Ref', 'Shad','Img']]
table1

In [ ]:
A1_set11 =A1_set1.head(3)
A1_set11

In [ ]:
for img in A1_set11['Img']:
  S5_double = img
  full_path_to_file2 = os.path.join(S5_double) 
  blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
  imagee = cv2.imread(S5_double)
  S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)

  S5meanrefA1_1 =  S5RGB_imgA1A1_1[1769:1881,2019:2131]
  S5meanA1_2 = S5RGB_imgA1A1_1[1770:1880,2015:2145]
  S5refA1_1 = np.array(S5meanrefA1_1[0])
  S5refA1_2 = np.array(S5meanA1_2[0])
  Rref = S5refA1_1[:,0].mean()
  Gref = S5refA1_1[:,1].mean()
  Bref = S5refA1_1[:,2].mean()
  R = S5refA1_2[:,0].mean()
  G = S5refA1_2[:,1].mean()
  B = S5refA1_2[:,2].mean()
    
  list_total1 = list()
  list_total1.append(Rref)
  list_total1.append(Gref)
  list_total1.append(Bref)
  list_total1.append(R)
  list_total1.append(G)
  list_total1.append(B)
  list_total2 = list()
  list_total2.append(list_total1) 

In [ ]:
cols=['R-ref', 'G-ref' , 'B-ref']
S1=pd.DataFrame(list_total1,columns=cols)
S1['Setting']='Set1'
S1

In [ ]:
pd.concat([S1,table1], axis=1)