<a href="https://colab.research.google.com/github/Kggzzz/Project_2021_matchingcolor/blob/main/Test_datapoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import cv2
import numpy as np

In [2]:
!pip install azure-storage-blob==2.1.0

     |████████████████████████████████| 88 kB 3.8 MB/s 
     |████████████████████████████████| 47 kB 4.8 MB/s 
     |████████████████████████████████| 3.6 MB 64.8 MB/s 


In [3]:
from azure.storage.blob import BlockBlobService
import os
blob_service_client = BlockBlobService(account_name='dent01', account_key='CuShY0B4TZJ84TjzPpaHxyrHOpO73aGXeCpdVq7x26OjIlQ1HOz+3DVc9pDEj9BdcEL8odFuTRF0mOAE+aCgiw==')

In [82]:
img = '342AE035-E0F5-4DEF-988E-27F570C725B2.png'

In [ ]:
list_total1 = list()
list_total2 = list()
list_total3 = list()
S5_double = img
full_path_to_file2 = os.path.join(S5_double) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(S5_double)
S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
S5meanrefA1_1 =  S5RGB_imgA1A1_1[1769:1881,2019:2131] #ลองดูพิกัดใหม่
S5meanA1_2 = S5RGB_imgA1A1_1[1770:1880,2015:2145]
S5meanrefA1_1 = np.array(S5meanrefA1_1[0])
S5meanA1_2 = np.array(S5meanA1_2[0])
S5rgbrefA1_1 = list()
S5rgbA1_2 = list()
for i in range(3):
  S5rgbrefA1_1.append(S5meanrefA1_1[:,i].mean())
  S5rgbA1_2.append(S5meanA1_2[:,i].mean())
list_total1.append(S5rgbrefA1_1)
list_total2.append(S5rgbA1_2)
list_total1[0].extend(list_total2[0])
list_total3 = list_total1 

In [ ]:
list_total3

[[231.90178571428572,
  215.35714285714286,
  184.02678571428572,
  231.0,
  214.5076923076923,
  182.98461538461538]]

In [ ]:
S5rgbrefA1_1

[231.90178571428572, 215.35714285714286, 184.02678571428572]

In [ ]:
list_total3

[[231.90178571428572,
  215.35714285714286,
  184.02678571428572,
  231.0,
  214.5076923076923,
  182.98461538461538]]

In [ ]:
list_total

[([231.90178571428572, 215.35714285714286, 184.02678571428572],
  [231.0, 214.5076923076923, 182.98461538461538])]

In [ ]:
S5meanrefA1_1.shape

(112, 3)

In [ ]:
G1[0]

array([[225, 206, 176],
       [226, 207, 177],
       [225, 206, 176],
       ...,
       [ 57,  55,  58],
       [ 62,  60,  63],
       [ 63,  61,  64]], dtype=uint8)

In [ ]:
# list_total = list()
# S5_double = img
# full_path_to_file2 = os.path.join(S5_double) 
# blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
# imagee = cv2.imread(S5_double)
# S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
# S5meanrefA1_1 = list()
# for i in range(S5RGB_imgA1A1_1.shape[0]): 
#     for j in range(S5RGB_imgA1A1_1.shape[1]): 
#           if 1769<i<1881 and 2019<j<2131 :
#              new_img = S5RGB_imgA1A1_1[i][j]
#           if 1770<i<1880 and 2015<j<2145 :
#              new_img = S5RGB_imgA1A1_1[i][j]
# S5meanrefA1_1 = np.array(S5meanrefA1_1)
# S5meanA1_2 = np.array(S5meanrefA1_1)
# S5rgbrefA1_1 = list()
# for i in range(3):
#   S5rgbrefA1_1.append(S5meanrefA1_1[:,i].mean())
#   S5rgbrefA1_1.append(S5meanA1_2[:,i].mean())
# list_total.append(S5rgbrefA1_1)

In [ ]:
new_img

array([225, 206, 176], dtype=uint8)

In [ ]:
S5RGB_imgA1A1_1.shape

(3024, 4032, 3)

In [ ]:
# list_total = list()
# S5_double = img
# full_path_to_file2 = os.path.join(S5_double) 
# blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
# imagee = cv2.imread(S5_double)
# S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
# S5meanrefA1_1 = list()
# for i in range(S5RGB_imgA1A1_1.shape[0]): 
#   for j in range(S5RGB_imgA1A1_1.shape[1]): 
#       if 1769<i<1881 and 2019<j<2131 :
#           S5meanrefA1_1.append(S5RGB_imgA1A1_1[i][j]) 
#       if 1770<i<1880 and 2015<j<2145 :
#           S5meanrefA1_1.append(S5RGB_imgA1A1_1[i][j])
# S5meanrefA1_1 = np.array(S5meanrefA1_1)
# S5meanA1_2 = np.array(S5meanrefA1_1)
# S5rgbrefA1_1 = list()
# for i in range(3):
#   S5rgbrefA1_1.append(S5meanrefA1_1[:,i].mean())
#   S5rgbrefA1_1.append(S5meanA1_2[:,i].mean())
# list_total.append(S5rgbrefA1_1)

In [ ]:
S5meanrefA1_1

array([[230, 214, 181],
       [231, 215, 182],
       [233, 217, 184],
       ...,
       [222, 203, 173],
       [222, 203, 173],
       [225, 206, 176]], dtype=uint8)

In [ ]:
S5meanrefA1_1.shape

(26382, 3)

In [ ]:
list_total12 = list()
list_total22 = list()
S5_double2 = img
image2  = cv2.imread(S5_double2) #RGB
S1RGB_imgA1A1_12= cv2.cvtColor(image2, cv2.COLOR_BGR2RGB)
S1meanrefA1_12 = list()
for i in range(S1RGB_imgA1A1_12.shape[0]): 
  for j in range(S1RGB_imgA1A1_12.shape[1]): 
        if 1769<i<1881 and 2019<j<2131 :
          S1meanrefA1_12.append(S1RGB_imgA1A1_12[i][j]) 
S1meanrefA1_12 = np.array(S1meanrefA1_12)
S1rgbrefA1_12 = list()
for i in range(3):
   S1rgbrefA1_12.append(S1meanrefA1_12[:,i].mean())
list_total12.append(S1rgbrefA1_12)

S1meanA1_22 = list()
for i in range(S1RGB_imgA1A1_12.shape[0]): 
  for j in range(S1RGB_imgA1A1_12.shape[1]): 
      if 1770<i<1880 and 2015<j<2145 :
        S1meanA1_22.append(S1RGB_imgA1A1_12[i][j])  
S1meanA1_22 = np.array(S1meanA1_22)
# S1rgbA1_2 = list()
# for i in range(3):
#   S1rgbA1_2.append(S1meanA1_2[:,i].mean())
# list_total2.append(S1rgbA1_2)
# list_total1[0].extend(list_total2[0])
# list_total3 = list_total1

In [ ]:
list_total3 

[[227.33065497930363,
  209.00048697345994,
  176.54403051700348,
  227.05412132849727,
  208.74084346774768,
  176.32529692056042]]

In [ ]:
S1meanrefA1_12

array([[230, 214, 181],
       [231, 215, 182],
       [233, 217, 184],
       ...,
       [222, 203, 173],
       [222, 203, 173],
       [225, 206, 176]], dtype=uint8)

In [ ]:
S1meanrefA1_12.shape

(12321, 3)

In [ ]:
# list_total1 = list()
# for img in A1_set11['Img']:
#   S1_double = img
#   full_path_to_file2 = os.path.join(S1_double) 
#   blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
#   imgS1_A1A1_1  = cv2.imread(S1_double) #RGB
#   S1RGB_imgA1A1_1= cv2.cvtColor(imgS1_A1A1_1, cv2.COLOR_BGR2RGB)
#   S1meanrefA1_1 = list()
#   S1meanrefA1_2 = list()
#   for i in range(S1RGB_imgA1A1_1.shape[0]): 
#      for j in range(S1RGB_imgA1A1_1.shape[1]): 
#                 if 1769<i<1881 and 2019<j<2131 :
#                   S1meanrefA1_1.append(S1RGB_imgA1A1_1[i][j]) 
#                 if 1770<i<1880 and 2015<j<2145 :
#                   S1meanrefA1_2.append(S1RGB_imgA1A1_1[i][j])
#   S1meanrefA1_1 = np.array(S1meanrefA1_1)
#   S1meanrefA1_2 = np.array(S1meanrefA1_2)
#   S1rgbrefA1_1 = list()
#   S1rgbrefA1_2 = list()
#   for i in range(3):
#     S1rgbrefA1_1.append(S1meanrefA1_1[:,i].mean())
#     S1rgbrefA1_2.append(S1meanrefA1_2[:,i].mean())
#   list_total1.append((S1rgbrefA1_1,S1rgbrefA1_2))

In [92]:
S5_double = img
full_path_to_file2 = os.path.join(S5_double) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(S5_double)
S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)

S5meanrefA1_1 =  S5RGB_imgA1A1_1[1769:1881,2019:2131]
S5meanA1_2 = S5RGB_imgA1A1_1[1770:1880,2015:2145]
S5refA1_1 = np.array(S5meanrefA1_1[0])
S5refA1_2 = np.array(S5meanA1_2[0])
Rref = S5refA1_1[:,0].mean()
Gref = S5refA1_1[:,1].mean()
Bref = S5refA1_1[:,2].mean()
R = S5refA1_2[:,0].mean()
G = S5refA1_2[:,1].mean()
B = S5refA1_2[:,2].mean()

list_total = list()
list_total.append(Rref)
list_total.append(Gref)
list_total.append(Bref)
list_total.append(R)
list_total.append(G)
list_total.append(B)

In [93]:
print("Rref:", Rref)
print("Gref:", Gref)
print("Bref:", Bref)
print("R:", R)
print("G:", G)
print("B:", B)

Rref: 231.90178571428572
Gref: 215.35714285714286
Bref: 184.02678571428572
R: 231.0
G: 214.5076923076923
B: 182.98461538461538


In [84]:
S5refA1_1.shape

(112, 3)

In [86]:
S5meanrefA1_1.shape

(112, 112, 3)

In [ ]:
# list_total

[231.90178571428572,
 215.35714285714286,
 184.02678571428572,
 231.0,
 214.5076923076923,
 182.98461538461538]

In [ ]:
# list_total2 = list()
# list_total2.append(list_total)

In [ ]:
# list_total2

[[231.90178571428572,
  215.35714285714286,
  184.02678571428572,
  231.0,
  214.5076923076923,
  182.98461538461538]]

#ตาราง

In [4]:
from google.colab import drive 
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
path = '/content/drive/My Drive/shadeimg/SVM shade'

In [6]:
import os

In [7]:
os.listdir(path)

['DD.xlsx',
 'CC.xlsx',
 'BB.xlsx',
 'Shade_AA.xlsx',
 'Shade_CC.xlsx',
 'Shade_DD.xlsx',
 'Shade_BB.xlsx',
 'AA.xlsx',
 'AA_2.xlsx',
 'Shad_A.xlsx',
 'Shad_B.xlsx',
 'Shad_C.xlsx',
 'Shad_D.xlsx',
 'Setting4.xlsx',
 'Color-checkerAA.xlsx',
 'Color-checkerBB.xlsx',
 'Color-checkerCC.xlsx',
 'Setting2.xlsx',
 'D3set51.csv',
 'Setting1.xlsx',
 'CheckerDD.xlsx',
 'Setting3.xlsx',
 'Setting6.xlsx',
 'Setting5.xlsx',
 'checkerShad_A .xlsx',
 'checkerShad_B.xlsx',
 'checkerShad_C.xlsx',
 'D3Set5-61.xlsx',
 'checkerShad_D.xlsx',
 'Color-checkerDD.xlsx']

In [55]:
AA = os.path.join(path,'Color-checkerDD.xlsx')

In [56]:
A1_set1= pd.read_excel(AA, sheet_name='D3_1')
A1_set1

ชื่อไฟล์ข้อมูล  ...                หมายเหตุ
0                                         NaN  ...                     NaN
1    6914F243-996E-49C6-B061-4B5873910254.png  ...  Duration 1/100 ISO 630
2    0F4CC07F-2FB9-430D-8A7D-256916A5E5AC.png  ...  Duration 1/100 ISO 630
3    D31A6339-9324-4718-8F1D-F9C86FF1CAC1.png  ...  Duration 1/100 ISO 630
4    3AD826D5-B618-4F47-BB57-2052C33EFAAE.png  ...  Duration 1/100 ISO 630
..                                        ...  ...                     ...
160  4BA3C8CF-5469-4252-A5C9-D702506A49EB.png  ...  Duration 1/100 ISO 630
161  FAAE3E0E-8887-4F38-B98A-BB9B3AC9DDE9.png  ...  Duration 1/100 ISO 630
162  8D59BE41-F7B8-48AA-80D2-89C33B5C1139.png  ...  Duration 1/100 ISO 630
163  1CFB9D44-9FE7-404B-AC34-F96C5CF881C8.png  ...  Duration 1/100 ISO 630
164  95F3176B-A2FF-4A86-A11C-65F69D4900DE.png  ...  Duration 1/100 ISO 630

[165 rows x 7 columns]

In [57]:
A1_set1.rename(columns={"รหัสเฉดไกด์": "Ref"},inplace=True)

In [58]:
A1_set1.rename(columns={"Unnamed: 2":"Shad"},inplace=True)

In [59]:
A1_set1.rename(columns={"ชื่อไฟล์ข้อมูล":"Img"},inplace=True)

In [60]:
A1_set1 = A1_set1.iloc[3:162,:]

In [61]:
table1= A1_set1[['Ref', 'Shad','Img']]
table1

Ref Shad                                       Img
3    D3   A1  D31A6339-9324-4718-8F1D-F9C86FF1CAC1.png
4    D3   A1  3AD826D5-B618-4F47-BB57-2052C33EFAAE.png
5    D3   A1  14BDB65A-A5B9-48B4-9F79-1C078570A88D.png
6    D3   A1  9131592F-9798-4457-ACD3-8109CCA36224.png
7    D3   A1  653769F4-F724-4660-A3EE-76C3101A90E5.png
..   ..  ...                                       ...
157  D3   D4  6FDBB895-E3C9-419F-9B20-3FBB5B0A3A2B.png
158  D3   D4  2F892491-DF86-4A29-9407-01669B26879A.png
159  D3   D4  B9632EBA-E90D-4574-8ED0-6E880ECBAD76.png
160  D3   D4  4BA3C8CF-5469-4252-A5C9-D702506A49EB.png
161  D3   D4  FAAE3E0E-8887-4F38-B98A-BB9B3AC9DDE9.png

[159 rows x 3 columns]

In [64]:
A1_set11 = A1_set1
A1_set11

Img  ...                หมายเหตุ
3    D31A6339-9324-4718-8F1D-F9C86FF1CAC1.png  ...  Duration 1/100 ISO 630
4    3AD826D5-B618-4F47-BB57-2052C33EFAAE.png  ...  Duration 1/100 ISO 630
5    14BDB65A-A5B9-48B4-9F79-1C078570A88D.png  ...  Duration 1/100 ISO 630
6    9131592F-9798-4457-ACD3-8109CCA36224.png  ...  Duration 1/100 ISO 630
7    653769F4-F724-4660-A3EE-76C3101A90E5.png  ...  Duration 1/100 ISO 630
..                                        ...  ...                     ...
157  6FDBB895-E3C9-419F-9B20-3FBB5B0A3A2B.png  ...  Duration 1/100 ISO 630
158  2F892491-DF86-4A29-9407-01669B26879A.png  ...  Duration 1/100 ISO 630
159  B9632EBA-E90D-4574-8ED0-6E880ECBAD76.png  ...  Duration 1/100 ISO 630
160  4BA3C8CF-5469-4252-A5C9-D702506A49EB.png  ...  Duration 1/100 ISO 630
161  FAAE3E0E-8887-4F38-B98A-BB9B3AC9DDE9.png  ...  Duration 1/100 ISO 630

[159 rows x 7 columns]

In [70]:
import pandas as pd

In [79]:
for img in A1_set11['Img']:
    S5_double = img
    full_path_to_file2 = os.path.join(S5_double) 
    blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
    imagee = cv2.imread(S5_double)
    S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)

    S5meanrefA1_1 =  S5RGB_imgA1A1_1[1769:1881,2019:2131]
    S5meanA1_2 = S5RGB_imgA1A1_1[1770:1880,2015:2145]
    S5refA1_1 = np.array(S5meanrefA1_1[0])
    S5refA1_2 = np.array(S5meanA1_2[0])
    Rref = S5refA1_1[:,0].mean()
    Gref = S5refA1_1[:,1].mean()
    Bref = S5refA1_1[:,2].mean()
    R = S5refA1_2[:,0].mean()
    G = S5refA1_2[:,1].mean()
    B = S5refA1_2[:,2].mean()
    
    list_total = list()
    list_total.append(Rref)
    list_total.append(Gref)
    list_total.append(Bref)
    list_total.append(R)
    list_total.append(G)
    list_total.append(B)
    list_total2 = list()
    list_total2.append(list_total) 

In [80]:
list_total2

[[224.55357142857142,
  202.25892857142858,
  151.08035714285714,
  224.93846153846152,
  202.53076923076924,
  151.5]]

In [81]:
cols=['R-ref', 'G-ref' , 'B-ref', 'R-Shad', 'G-Shad', 'B-Shad']
S1=pd.DataFrame(list_total2,columns=cols)
S1['Setting']='Set1'
S1

R-ref       G-ref       B-ref      R-Shad      G-Shad  B-Shad Setting
0  224.553571  202.258929  151.080357  224.938462  202.530769   151.5    Set1

In [ ]:
pd.concat([S1,table1], axis=1)