<a href="https://colab.research.google.com/github/Kggzzz/Project_2021_matchingcolor/blob/main/Test_datapoint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import cv2
import numpy as np

In [2]:
!pip install azure-storage-blob==2.1.0

     |████████████████████████████████| 88 kB 4.7 MB/s 
     |████████████████████████████████| 47 kB 5.3 MB/s 
     |████████████████████████████████| 3.6 MB 18.8 MB/s 


In [3]:
from azure.storage.blob import BlockBlobService
import os
blob_service_client = BlockBlobService(account_name='dent01', account_key='CuShY0B4TZJ84TjzPpaHxyrHOpO73aGXeCpdVq7x26OjIlQ1HOz+3DVc9pDEj9BdcEL8odFuTRF0mOAE+aCgiw==')

In [4]:
img = '342AE035-E0F5-4DEF-988E-27F570C725B2.png'

In [65]:
list_total1 = list()
list_total2 = list()
list_total3 = list()
S5_double = img
full_path_to_file2 = os.path.join(S5_double) 
blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
imagee = cv2.imread(S5_double)
S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
S5meanrefA1_1 =  S5RGB_imgA1A1_1[1769:1881,2019:2131]
S5meanA1_2 = S5RGB_imgA1A1_1[1770:1880,2015:2145]
S5meanrefA1_1 = np.array(S5meanrefA1_1[0])
S5meanA1_2 = np.array(S5meanA1_2[0])
S5rgbrefA1_1 = list()
S5rgbA1_2 = list()
for i in range(3):
  S5rgbrefA1_1.append(S5meanrefA1_1[:,i].mean())
  S5rgbA1_2.append(S5meanA1_2[:,i].mean())
list_total1.append(S5rgbrefA1_1)
list_total2.append(S5rgbA1_2)
list_total1[0].extend(list_total2[0])
list_total3 = list_total1 

In [61]:
S5rgbrefA1_1

[231.90178571428572, 215.35714285714286, 184.02678571428572]

In [66]:
list_total3

[[231.90178571428572,
  215.35714285714286,
  184.02678571428572,
  231.0,
  214.5076923076923,
  182.98461538461538]]

In [63]:
list_total

[([231.90178571428572, 215.35714285714286, 184.02678571428572],
  [231.0, 214.5076923076923, 182.98461538461538])]

In [54]:
S5meanrefA1_1.shape

(112, 3)

In [10]:
G1[0]

array([[225, 206, 176],
       [226, 207, 177],
       [225, 206, 176],
       ...,
       [ 57,  55,  58],
       [ 62,  60,  63],
       [ 63,  61,  64]], dtype=uint8)

In [ ]:
# list_total = list()
# S5_double = img
# full_path_to_file2 = os.path.join(S5_double) 
# blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
# imagee = cv2.imread(S5_double)
# S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
# S5meanrefA1_1 = list()
# for i in range(S5RGB_imgA1A1_1.shape[0]): 
#     for j in range(S5RGB_imgA1A1_1.shape[1]): 
#           if 1769<i<1881 and 2019<j<2131 :
#              new_img = S5RGB_imgA1A1_1[i][j]
#           if 1770<i<1880 and 2015<j<2145 :
#              new_img = S5RGB_imgA1A1_1[i][j]
# S5meanrefA1_1 = np.array(S5meanrefA1_1)
# S5meanA1_2 = np.array(S5meanrefA1_1)
# S5rgbrefA1_1 = list()
# for i in range(3):
#   S5rgbrefA1_1.append(S5meanrefA1_1[:,i].mean())
#   S5rgbrefA1_1.append(S5meanA1_2[:,i].mean())
# list_total.append(S5rgbrefA1_1)

In [ ]:
new_img

array([225, 206, 176], dtype=uint8)

In [ ]:
S5RGB_imgA1A1_1.shape

(3024, 4032, 3)

In [55]:
# list_total = list()
# S5_double = img
# full_path_to_file2 = os.path.join(S5_double) 
# blob_service_client.get_blob_to_path('shadeimg', full_path_to_file2, full_path_to_file2)
# imagee = cv2.imread(S5_double)
# S5RGB_imgA1A1_1 = cv2.cvtColor(imagee, cv2.COLOR_BGR2RGB)
# S5meanrefA1_1 = list()
# for i in range(S5RGB_imgA1A1_1.shape[0]): 
#   for j in range(S5RGB_imgA1A1_1.shape[1]): 
#       if 1769<i<1881 and 2019<j<2131 :
#           S5meanrefA1_1.append(S5RGB_imgA1A1_1[i][j]) 
#       if 1770<i<1880 and 2015<j<2145 :
#           S5meanrefA1_1.append(S5RGB_imgA1A1_1[i][j])
# S5meanrefA1_1 = np.array(S5meanrefA1_1)
# S5meanA1_2 = np.array(S5meanrefA1_1)
# S5rgbrefA1_1 = list()
# for i in range(3):
#   S5rgbrefA1_1.append(S5meanrefA1_1[:,i].mean())
#   S5rgbrefA1_1.append(S5meanA1_2[:,i].mean())
# list_total.append(S5rgbrefA1_1)

In [56]:
S5meanrefA1_1.shape

(26382, 3)

In [57]:
S5meanrefA1_1

array([[230, 214, 181],
       [231, 215, 182],
       [233, 217, 184],
       ...,
       [222, 203, 173],
       [222, 203, 173],
       [225, 206, 176]], dtype=uint8)